function jokesGenerator(){
    let jokeValue = document.querySelector('#jokes-para');
    
    let jokes = [
        "Why don't scientists trust atoms? Because they make up everything!",
        "I told my wife she was drawing her eyebrows too high. She looked surprised.",
        "What do you call fake spaghetti? An impasta!",
        "Why did the scarecrow win an award? Because he was outstanding in his field!",
        "I'm reading a book on anti-gravity. It's impossible to put down!",
        "Why don't skeletons fight each other? They don't have the guts.",
        "What do you call cheese that isn't yours? Nacho cheese!",
        "Why couldn't the bicycle stand up by itself? It was two-tired.",
        "Parallel lines have so much in common. It’s a shame they’ll never meet.",
        "I'm reading a book on the history of glue. I just can't seem to put it down!",
        "Why don’t scientists trust stairs? Because they’re always up to something.",
        "I told my wife she should embrace her mistakes. She gave me a hug.",
        "Why did the coffee file a police report? It got mugged.",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "I told my computer I needed a break and now it won't stop sending me vacation ads.",
        "What do you get when you cross a snowman and a vampire? Frostbite.",
        "I'm trying to organize a hide and seek competition but it's hard to find good players. They're always hiding.",
        "Why did the math book look sad? Because it had too many problems.",
        "What do you call an alligator in a vest? An in-vest-igator!",
        "I'm on a whiskey diet. I've lost three days already!",
        "Why don't skeletons fight each other? They don't have the guts.",
        "I'm writing a book on hurricanes and tornadoes. It's a whirlwind of excitement!",
        "Why was the math book sad? Because it had too many problems.",
        "What did one ocean say to the other ocean? Nothing, they just waved.",
        "I used to play piano by ear, but now I use my hands.",
        "Why did the scarecrow win an award? Because he was outstanding in his field!",
        "I told my wife she was drawing her eyebrows too high. She looked surprised.",
        "What's orange and sounds like a parrot? A carrot.",
        "Why don't scientists trust atoms? Because they make up everything!",
        "Parallel lines have so much in common. It's a shame they'll never meet.",
        "I'm trying to organize a hide and seek competition but it's hard to find good players. They're always hiding.",
        "Why don't skeletons fight each other? They don't have the guts.",
        "What do you call an alligator in a vest? An investigator!",
        "I'm reading a book on anti-gravity. It's impossible to put down!",
        "Why was the math book sad? Because it had too many problems.",
        "What did one ocean say to the other ocean? Nothing, they just waved.",
        "I used to play piano by ear, but now I use my hands.",
        "Why did the coffee file a police report? It got mugged.",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "I told my computer I needed a break and now it won't stop sending me vacation ads.",
        "What do you get when you cross a snowman and a vampire? Frostbite.",
        "I'm on a whiskey diet. I've lost three days already!",
        "Why don’t scientists trust stairs? Because they’re always up to something.",
        "I told my wife she should embrace her mistakes. She gave me a hug.",
        "What do you call cheese that isn't yours? Nacho cheese!",
        "Why couldn't the bicycle stand up by itself? It was two-tired.",
        "I'm reading a book on the history of glue. I just can't seem to put it down!",
        "Why do cows wear bells? Because their horns don’t work.",
        "Why don’t eggs tell jokes? They’d crack each other up!",
        "What’s a vampire’s favorite fruit? A blood orange.",
        "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
        "I told my wife she should embrace her mistakes. She gave me a hug.",
        "What do you call a belt made out of watches? A waist of time.",
        "I'm reading a book on anti-gravity. It's impossible to put down!",
        "Why did the coffee file a police report? It got mugged."
      ];

    let jokesGen = jokes[Math.floor(Math.random()*jokes.length)];
    jokeValue.innerText = jokesGen;
}